services:
  php-apache:
    depends_on:
      - mysql
    build:
      context: ./docker/php_apache_dockerfile
    volumes:
      - ./htdocs:/var/www/html
      - ./docker/config_files/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php_apache_dockerfile/msmtprc:/etc/msmtprc
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    ports:
      - 80:80
      - 443:443
  phpmyadmin:
    depends_on:
      - mysql
      - php-apache
    image: phpmyadmin:5.1.3-apache
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
  mysql:
    image: mysql:8.0.29-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
